env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  semi: 
    - error
    - always
  quotes:
    - error
    - single
  no-multi-spaces: 0
  no-param-reassign: 0
  one-var: 0
  no-console: 0
  linebreak-style: 0
  no-underscore-dangle: ["error", { "allow": ["_id"] }]
  max-len: ["error", { "code": 140, "ignoreStrings": true, "ignoreTemplateLiterals": true }]
  max-nested-callbacks: ["error", 3]
  max-params: ["error", 8]
  max-depth: ["error", 5]
  max-lines-per-function: ["error", 120]
  complexity: ["error", 16]
  class-methods-use-this: 0
  arrow-parens: ["error", "always"]
  object-curly-newline: ["error", { "minProperties": 8, "consistent": true }]
  import/extensions: ["error", { "ts": "never" }]
  import/no-unresolved: error
  lines-between-class-members: ["error", "always", { "exceptAfterSingleLine": true }]
settings:
  import/parsers:
    "@typescript-eslint/parser":
    - ".ts"
    - ".tsx"
  import/resolver:
    typescript:
      project:
      - "*/tsconfig.json"
